"""Small dependency-free mobile capture page served only by a token-scoped session."""

MOBILE_PAGE = r'''<!doctype html>
<html lang="en"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
<meta name="referrer" content="no-referrer"><title>Upasthiti Smart Capture</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f0f4f8;color:#1a1a2e;font:16px system-ui}
main{max-width:560px;margin:auto;padding:16px}header{font-weight:750;color:#0d47a1;font-size:23px;margin:8px 0 14px}
.card{background:#fff;border:1px solid #dde3ea;border-radius:14px;padding:16px;margin:12px 0}h2{font-size:19px;margin:4px 0}
p{line-height:1.4;color:#5c6370}.pick,button{display:block;width:100%;margin:8px 0;padding:14px;border:1px solid #d5dfeb;border-radius:10px;background:#f8fbff;color:#1565c0;font:700 16px system-ui;text-align:center}
.pick{cursor:pointer}button.primary{background:#1565c0;color:#fff;border:0}button:disabled{opacity:.45}
.photos{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px}.photo{border:1px solid #dde3ea;border-radius:10px;padding:8px;min-width:0}
.photo img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:7px;background:#e8edf3}.photo small{display:block;overflow-wrap:anywhere;margin:5px 0;color:#5c6370}
.photo button{padding:10px 6px;font-size:14px;margin:5px 0}.photo button.remove{background:#fff4f2;color:#a5281b}
.metrics{display:grid;grid-template-columns:1fr 1fr;gap:8px}.metric{background:#f5f8fc;border-radius:8px;padding:10px}.metric b{display:block;font-size:20px;color:#0d47a1}
.status{min-height:24px;color:#2e7d32;font-weight:650;overflow-wrap:anywhere}.warning{color:#a35300}.muted{font-size:13px}
</style>
<main><header>UPASTHITI · SMART CAPTURE</header>
<section class="card"><h2>Capture classroom photos</h2><p>Review each photo before uploading. Photos go directly to the laptop over this local network.</p>
<label class="pick">＋ Take a photo<input id="camera" type="file" accept="image/*" capture="environment" hidden></label>
<label class="pick">＋ Choose photos<input id="gallery" type="file" accept="image/jpeg,image/png,image/bmp" multiple hidden></label>
<div id="photos" class="photos"></div><p id="count" aria-live="polite">Photos selected: 0</p>
<button id="send" class="primary" disabled>Upload selected photos</button><button id="retry" hidden>Retry failed uploads</button><button id="finish">Finish Anyway / Review on laptop</button>
<div id="status" class="status" role="status" aria-live="polite">Ready</div></section>
<section id="analysis" class="card" hidden><h2>Capture feedback</h2><div class="metrics">
<div class="metric">Confidently observed<b id="confident">0 / 0</b></div><div class="metric">Coverage<b id="coverage">0%</b></div>
<div class="metric">Faces detected<b id="detected">0</b></div><div class="metric">Need review<b id="uncertain">0</b></div>
<div class="metric">Unidentified faces<b id="unknown">0</b></div><div class="metric">Not yet observed<b id="missing">0</b></div></div>
<p id="guidance" class="warning"></p><p id="similar" class="muted" hidden>This photo looks similar to an earlier capture. Check the laptop preview and remove it there if accidental.</p></section>
<p class="muted">Coverage counts unique students with a non-uncertain match in this session. It is not a recognition-accuracy score. The laptop performs all analysis.</p></main>
<script>
const base=location.pathname.replace(/\/$/,"");const camera=document.getElementById("camera"),gallery=document.getElementById("gallery"),send=document.getElementById("send"),retry=document.getElementById("retry"),finish=document.getElementById("finish"),status=document.getElementById("status"),count=document.getElementById("count"),list=document.getElementById("photos");
let items=[],retakeId=null,busy=false;function revoke(item){if(item.url)URL.revokeObjectURL(item.url)}
function addFiles(files,isCamera){for(const file of files){if(!file.type.startsWith("image/")){status.textContent="Choose a supported photo.";continue}if(file.size>12*1024*1024){status.textContent="Each photo must be smaller than 12 MB.";continue}const item={id:(crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random()),file,url:URL.createObjectURL(file),camera:isCamera,selected:false,state:"preview"};if(retakeId){const index=items.findIndex(x=>x.id===retakeId);if(index>=0){revoke(items[index]);items.splice(index,1,item)}else items.push(item);retakeId=null}else items.push(item)}render()}
function render(){list.replaceChildren();let n=0,failed=0;for(const item of items){if(item.selected&&item.state==="preview")n++;if(item.state==="failed")failed++;const card=document.createElement("article");card.className="photo";const img=document.createElement("img");img.src=item.url;img.alt="Photo preview";card.append(img);const name=document.createElement("small");name.textContent=item.file.name;card.append(name);const state=document.createElement("small");state.textContent=item.state==="preview"?(item.selected?"Selected for upload":"Review this photo"):item.state==="uploading"?(item.progress||"Uploading…"):item.state==="uploaded"?"Uploaded · analyzing on laptop":item.state==="failed"?"Upload failed · retry available":"Duplicate · not uploaded";card.append(state);if(item.state==="preview"){const use=document.createElement("button");use.textContent=item.selected?"✓ Use This Photo":"Use This Photo";use.onclick=()=>{item.selected=!item.selected;render()};card.append(use);const retake=document.createElement("button");retake.textContent="Retake";retake.onclick=()=>{retakeId=item.id;camera.click()};card.append(retake);const remove=document.createElement("button");remove.className="remove";remove.textContent="Remove";remove.onclick=()=>{revoke(item);items=items.filter(x=>x!==item);render()};card.append(remove)}list.append(card)}count.textContent=`Photos selected: ${n}`;send.disabled=busy||!n;retry.hidden=busy||!failed}
function uploadOne(item,index,total){return new Promise(resolve=>{const xhr=new XMLHttpRequest();xhr.open("POST",base+"/upload");xhr.setRequestHeader("Content-Type",item.file.type||"application/octet-stream");xhr.setRequestHeader("X-Filename",encodeURIComponent(item.file.name));item.state="uploading";item.progress=`Uploading ${index} of ${total} · 0%`;render();xhr.upload.onprogress=e=>{if(e.lengthComputable){item.progress=`Uploading ${index} of ${total} · ${Math.round(100*e.loaded/e.total)}%`;status.textContent=item.progress;render()}};xhr.onload=()=>{let data={};try{data=JSON.parse(xhr.responseText)}catch{}if(xhr.status>=200&&xhr.status<300){item.state="uploaded";item.selected=false}else if(xhr.status===409){item.state="duplicate";item.selected=false;status.textContent="This identical photo was already received; it was not uploaded again."}else{item.state="failed";item.selected=true;status.textContent=data.error||"Upload failed. Retry this photo or remove it."}resolve(xhr.status>=200&&xhr.status<300||xhr.status===409)};xhr.onerror=()=>{item.state="failed";item.selected=true;status.textContent="Connection interrupted. Check Wi-Fi and retry the failed photo.";resolve(false)};xhr.send(item.file)})}
async function upload(mode){if(busy)return;const batch=items.filter(x=>mode==="retry"?x.state==="failed":x.selected&&x.state==="preview");if(!batch.length)return;busy=true;render();status.textContent="Uploading selected photos…";let ok=0;for(let i=0;i<batch.length;i++){if(await uploadOne(batch[i],i+1,batch.length))ok++}busy=false;const failed=items.filter(x=>x.state==="failed").length;status.textContent=failed?`${ok} uploaded or already received · ${failed} failed. Retry failed uploads.`:`${ok} photo${ok===1?"":"s"} uploaded. Laptop analysis is updating.`;render()}
camera.onchange=()=>{addFiles(camera.files,true);camera.value=""};gallery.onchange=()=>{addFiles(gallery.files,false);gallery.value=""};send.onclick=()=>upload("selected");retry.onclick=()=>upload("retry");finish.onclick=async()=>{if(busy){status.textContent="Wait for the current upload to finish, then choose Finish Anyway.";return}if(items.some(x=>x.state==="preview"&&x.selected||x.state==="failed")){if(!window.confirm("Some selected or failed photos have not uploaded. Finish with the photos already received by the laptop?"))return}finish.disabled=true;status.textContent="Asking the laptop to finish and open review…";try{const r=await fetch(base+"/finish",{method:"POST",cache:"no-store"});if(!r.ok)throw Error();status.textContent="Finish requested. Continue review on the laptop."}catch{status.textContent="The session may have ended. Check the laptop."}};
async function poll(){try{const response=await fetch(base+"/status",{cache:"no-store"});if(response.status===410||response.status===404){status.textContent="Session expired or closed. Ask the laptop user to start a new capture.";send.disabled=true;retry.disabled=true;finish.disabled=true;return}if(!response.ok)throw Error();const data=await response.json(),a=data.analysis||{};if(data.connected&&status.textContent==="Ready")status.textContent="Connected to laptop · ready";if(data.finish_requested){finish.disabled=true;status.textContent="Finish requested. Continue review on the laptop."}if(a.state&&a.state!=="waiting"){document.getElementById("analysis").hidden=false;document.getElementById("confident").textContent=`${a.confidently_observed||0} / ${a.total_students||0}`;document.getElementById("coverage").textContent=`${a.coverage_percent||0}%`;document.getElementById("detected").textContent=a.detected_faces||0;document.getElementById("uncertain").textContent=a.uncertain_students||0;document.getElementById("unknown").textContent=a.unknown_faces||0;document.getElementById("missing").textContent=a.not_yet_observed||0;document.getElementById("guidance").textContent=a.guidance||"";document.getElementById("similar").hidden=!a.similar_to_previous;if(a.state==="analyzing"&&!busy&&!data.finish_requested)status.textContent="Analyzing on laptop…";else if(a.state==="ready"&&!data.finish_requested)status.textContent=a.another_capture_suggested?"Analysis complete · another capture may help":"Analysis complete · review on laptop";else if(a.state==="partial"&&!data.finish_requested)status.textContent="Analysis incomplete · finish to continue with review"}}catch{if(status.textContent==="Ready")status.textContent="Connecting to laptop…"}setTimeout(poll,2200)}
window.addEventListener("pagehide",()=>items.forEach(revoke));poll();
</script></html>'''
